---
# tasks file for gitlab

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Install GitLab dependencies.
  package: name={{ item }} state=present
  with_items:
    - openssh-server
    - postfix
    - curl
    - openssl
    - tzdata

- name: Download gitlab repo RedHat-like
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh dest=/usr/src/gitlab.rpm.sh mode=0755 validate_certs=no
  when: not gitlab_file.stat.exists

- name: Install gitlab repo RedHat-Like
  shell: /usr/src/gitlab.rpm.sh
  when: ansible_os_family == "RedHat"
  when: not gitlab_file.stat.exists

- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Copy GitLab configuration file.
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
